### ISSUE TITLE
simple-knn not found

### ISSUE THREAD

**Issue by Saksham209** [Fictionarry/TalkingGaussian#11]
The link to simple-knn provided does not work, could you please check this:
![simp_er](https://github.com/Fictionarry/TalkingGaussian/assets/135584003/50c72319-3cae-4c52-841b-3ab203662355)

**Comment by Fictionarry** [comment]
simple_knn is from https://gitlab.inria.fr/bkerbl/simple-knn.git, which is not a github repo. See the [.gitmodules](https://github.com/Fictionarry/TalkingGaussian/blob/main/.gitmodules) file.
