### ISSUE TITLE
What's the PyMCube version?

### ISSUE THREAD

**Issue by Net-Maker** [Fictionarry/TalkingGaussian#13]
I use conda to install the environment, the latest version of PyMCube requires numpy~=2.0, which is impossible in python 3.7.13.
I turned to install PyMCube==0.1.4, is the version right?

**Comment by Fictionarry** [comment]
I have also found this problem recently. 0.1.4 works well in my previous environment. You can just ignore this dependency unless some problems happen. It needs some time for me to confirm whether PyMCube is necessary, as I have forgotten why I added it into the environment 😅

**Comment by Net-Maker** [comment]
haha, anyway, thanks for your fast reply.
