### ISSUE TITLE
Cannot finish pre-processing video

### ISSUE THREAD

**Issue by rawrshah** [Fictionarry/TalkingGaussian#16]
Hey!

During pre-process after getting focals I'm getting error 

nvrtc: error: invalid value for --gpu-architecture (-arch)

and script finishes with error 

FileNotFoundError: [Errno 2] No such file or directory: 'data/bud/track_params.pt'

What can be the cause?

**Comment by Fictionarry** [comment]
I guess it's raised by pytorch3d. It may be caused by you are using a GPU like RTX 40xx that needs higher version CUDA. If so, you may update pytorch version to 1.13.1 + CUDA 11.7 or higher.

**Comment by Joy-xuaxua** [comment]
> I guess it's raised by pytorch3d. It may be caused by you are using a GPU like RTX 40xx that needs higher version CUDA. If so, you may update pytorch version to 1.13.1 + CUDA 11.7 or higher.

Hi
I am using RTX 4090 with CUDA **11.3**. And pytorch I installed is for 11.3. I still meet this issue when running face_tracking. 
Could you please help me find the solution? Thank you!

**Comment by Fictionarry** [comment]
> > I guess it's raised by pytorch3d. It may be caused by you are using a GPU like RTX 40xx that needs higher version CUDA. If so, you may update pytorch version to 1.13.1 + CUDA 11.7 or higher.
> 
> Hi I am using RTX 4090 with CUDA **11.3**. And pytorch I installed is for 11.3. I still meet this issue when running face_tracking. Could you please help me find the solution? Thank you!

CUDA 11.3 does not support 40 series gpus. As mentioned, you may try a CUDA version later than 11.7.

**Comment by Joy-xuaxua** [comment]
> > > I guess it's raised by pytorch3d. It may be caused by you are using a GPU like RTX 40xx that needs higher version CUDA. If so, you may update pytorch version to 1.13.1 + CUDA 11.7 or higher.
> > 
> > 
> > Hi I am using RTX 4090 with CUDA **11.3**. And pytorch I installed is for 11.3. I still meet this issue when running face_tracking. Could you please help me find the solution? Thank you!
> 
> CUDA 11.3 does not support 40 series gpus. As mentioned, you may try a CUDA version later than 

Got it. Thank you so much for your quick reply! Have a nice weekend :)
