### ISSUE TITLE
train_face时 warm_up结束后loss变成nan，训练结束后测试，人非常抖

### ISSUE THREAD

**Issue by anliyuan** [Fictionarry/TalkingGaussian#17]
![BossHi-20240715210748](https://github.com/user-attachments/assets/cbcf3497-4d09-486e-8940-a0a609969dda)
求助！！！！

**Comment by WangHao-nlp** [comment]
我这边loss几个iteration后就会变成nan，暂时还不知道问题在哪，可能是我环境问题

**Comment by anliyuan** [comment]
> 我这边loss几个iteration后就会变成nan，暂时还不知道问题在哪，可能是我环境问题

可能是训练数据的问题。。

**Comment by SherlockSunset** [comment]
请问你们这个问题后面有解决吗？就是loss会变成NaN。
