### ISSUE TITLE
Training code / preprocessing

### ISSUE THREAD

**Issue by johndpope** [Fictionarry/TalkingGaussian#2]
I'm particularly interested in how you got the key points out for training.
I'm attempting to recreate an older paper - MegaPortraits - and I can't decide best way to extract the keypoints. 
https://github.com/johndpope/MegaPortrait-hack/issues/2
https://github.com/johndpope/MegaPortrait-hack/issues/3

**Comment by johndpope** [comment]
https://github.com/grey-eye/talking-heads/blob/1f8edb68ffa7b7a8e5d02a19ca39bdec5fc2d30c/dataset/dataset.py#L215



https://github.com/jacobwjs/photometric_optimization/blob/4e9db86eff665a30f23430419e023f1c7c9ef00b/models/generate_DFR_dataset.py#L15

https://github.com/SamsungLabs/NeuralHaircut/blob/1dbdd07797458e6e0000bd3a02f3092d419d1756/src/multiview_optimization/dataset/dataset.py



https://github.com/Zielon/metrical-tracker/blob/c2a517244759d7eeaa0e84893d6748e75293f81a/datasets/generate_dataset.py#L18



https://github.com/jacobwjs/photometric_optimization/blob/4e9db86eff665a30f23430419e023f1c7c9ef00b/models/generate_DFR_dataset.py#L15

**Comment by Fictionarry** [comment]
Hi, in fact I can't get what the "key points" exactly mean. Such a description does not seem to appear in our paper :)
