### ISSUE TITLE
训练走到train_face 报错

### ISSUE THREAD

**Issue by 8600862** [Fictionarry/TalkingGaussian#31]
[ITER 2000] Evaluating test: L1 0.16910051672082196 PSNR 11.699522570559852 [21/08 12:39:47]

[ITER 2000] Evaluating train: L1 0.16705973148345948 PSNR 11.797615051269531 [21/08 12:39:50]
Training progress:   8%|##########2                                                                                                                     | 4000/50000 [00:41<10:26, 73.40it/s, Loss=nan, Mouth=9.1-20.0]
/data/anaconda3/envs/talkinggaussian/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py:549: RuntimeWarning: invalid value encountered in cast
  tensor = (tensor * scale_factor).clip(0, 255).astype(np.uint8)

[ITER 4000] Evaluating test: L1 0.16910051672082196 PSNR 11.699522570559852 [21/08 12:40:12]

[ITER 4000] Evaluating train: L1 0.16705973148345948 PSNR 11.797615051269531 [21/08 12:40:15]
Traceback (most recent call last):
  File "/data/TalkingGaussian/train_face.py", line 402, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/data/TalkingGaussian/train_face.py", line 241, in training
    training_report(tb_writer, iteration, Ll1, loss, l1_loss, iter_start.elapsed_time(iter_end), testing_iterations, scene, motion_net, render if iteration < warm_step else render_motion, (pipe, background))
  File "/data/TalkingGaussian/train_face.py", line 373, in training_report
    tb_writer.add_histogram("scene/opacity_histogram", scene.gaussians.get_opacity, iteration)
  File "/data/anaconda3/envs/talkinggaussian/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 517, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime
  File "/data/anaconda3/envs/talkinggaussian/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 459, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "/data/anaconda3/envs/talkinggaussian/lib/python3.10/site-packages/torch/utils/tensorboard/summary.py", line 504, in make_histogram
    raise ValueError("The histogram is empty, please file a bug report.")
ValueError: The histogram is empty, please file a bug report.

**Comment by Fictionarry** [comment]
tensorboard的问题，可以把tensorboard换成tensorboardX试试

**Comment by 8600862** [comment]
> tensorboardX

**Comment by linhcentrio** [comment]
> tensorboard的问题，可以把tensorboard换成tensorboardX试试



> tensorboard的问题，可以把tensorboard换成tensorboardX试试



> tensorboard的问题，可以把tensorboard换成tensorboardX试试

how can i fix this error, pls help! you mean pip uninstall tensorboard?

**Comment by Fictionarry** [comment]
> how can i fix this error, pls help! you mean pip uninstall tensorboard?

try first
```
pip uninstall tensorboard
pip install tensorboardX
```
and change `from torch.utils.tensorboard import SummaryWriter` in all .py files into `from tensorboardX import SummaryWriter`
