### ISSUE TITLE
请问如果想在渲染时更换背景，该怎么操作呢？

### ISSUE THREAD

**Issue by Coooderr** [Fictionarry/TalkingGaussian#35]
感谢您开源如此优秀的工作！在ER-NeRF中，可以使用--bg_img传递图片路径进行修改，请问在TalkingGaussian中是否支持更换背景的功能？具体该如何做呢？谢谢！

**Comment by Fictionarry** [comment]
您好，背景默认读的是data/xxx文件夹下的bc.jpg，可以修改这里的路径，或者手动实现一下--bg_img
https://github.com/Fictionarry/TalkingGaussian/blob/5acdaaa4508ccbeefc29673abc540430fe077c1e/scene/dataset_readers.py#L105

**Comment by Coooderr** [comment]
> 您好，背景默认读的是data/xxx文件夹下的bc.jpg，可以修改这里的路径，或者手动实现一下--bg_img
> 
> https://github.com/Fictionarry/TalkingGaussian/blob/5acdaaa4508ccbeefc29673abc540430fe077c1e/scene/dataset_readers.py#L105

好的，谢谢！
