### ISSUE TITLE
How can i run it in realtime ?

### ISSUE THREAD

**Issue by Deltaidiots** [Fictionarry/TalkingGaussian#45]

**Comment by Fictionarry** [comment]
Hi, this project supports real-time inference speed over 100 FPS. If you want to run it streamingly with real-time visualization, you may need to do some engineering. A simple way is to keep the rendering in a loop and create a show window. Some references can be found here https://github.com/lipku/livetalking (webrtc) https://github.com/ashawkey/RAD-NeRF (with a local real-time visualizer)
