### ISSUE TITLE
Need Help!! "RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered"

### ISSUE THREAD

**Issue by jisoo-o** [Fictionarry/TalkingGaussian#51]
Hello, thank you for awesome work. I have been admiring your research from ER-NeRF and I also wanted to work on talking head using 3dgs. But, I cannot move forward from train_face.py, as it gets killed in the middle. How can I solve an "illegal memory access was encountered" error? 

My environment is, CUDA 11.1, torch 1.10.1+cu111, torchvision 0.11.2+cu111. (GPU: RTX3090)

And here is what I have executed and the error. 

bash scripts/train_xx.sh data/may output/may 2

Optimizing output/may
Output folder: output/may [20/11 20:44:12]
Tensorboard not available: not logging progress [20/11 20:44:12]
Found transforms_train.json file, assuming Blender data set! [20/11 20:44:12]
Reading Training Transforms [20/11 20:44:12]
5520it [00:00, 8853.93it/s]
5520it [02:12, 41.57it/s]
Reading Test Transforms [20/11 20:46:26]
553it [00:00, 9075.84it/s]
553it [00:12, 42.85it/s]
Generating random point cloud (2000)... [20/11 20:46:39]
Loading Training Cameras [20/11 20:46:39]
Loading Test Cameras [20/11 20:46:49]
Number of points at initialisation :  2000 [20/11 20:46:49]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off] [20/11 20:46:49]
Loading model from: /home/xxxx/anaconda3/envs/talkinggaussian/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth [20/11 20:46:50]
Training progress:   4%|##                                                 | 1990/50000 [00:20<07:43, 103.69it/s, Loss=0.03306, Mouth=5.7-16.6]/home/xxxx/anaconda3/envs/talkinggaussian/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)

[ITER 2000] Evaluating test: L1 0.013309760558369911 PSNR 28.43818022075452 [20/11 20:47:10]

[ITER 2000] Evaluating train: L1 0.013016213104128838 PSNR 28.495322036743165 [20/11 20:47:10]
Training progress:   6%|###1                                                | **3030**/50000 [00:31<13:15, 59.01it/s, Loss=0.01216, Mouth=6.4-17.3]Traceback (most recent call last):
  File "train_face.py", line 394, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_face.py", line 227, in training
    loss.backward()
  File "/home/xxxx/anaconda3/envs/talkinggaussian/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/xxxx/anaconda3/envs/talkinggaussian/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
**RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered**
Training progress:   6%|###1                                                | 3030/50000 [00:32<08:19, 94.02it/s, Loss=0.01216, Mouth=6.4-17.3]
Looking for config file in output/may/cfg_args
Config file found: output/may/cfg_args
Rendering output/may
Found transforms_train.json file, assuming Blender data set! [20/11 20:47:25]
Reading Test Transforms [20/11 20:47:25]
553it [00:00, 9651.27it/s]
553it [00:12, 44.79it/s]
Generating random point cloud (10000)... [20/11 20:47:38]
Loading Training Cameras [20/11 20:47:38]
Loading Test Cameras [20/11 20:47:42]
Number of points at initialisation :  10000 [20/11 20:47:43]
Traceback (most recent call last):
  File "synthesize_fuse.py", line 125, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.use_train, args.fast, args.dilate)
  File "synthesize_fuse.py", line 93, in render_sets
    (model_params, motion_params, model_mouth_params, motion_mouth_params) = torch.load(os.path.join(dataset.model_path, "chkpnt_fuse_latest.pth"))
  File "/home/xxxx/anaconda3/envs/talkinggaussian/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xxxx/anaconda3/envs/talkinggaussian/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xxxx/anaconda3/envs/talkinggaussian/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'output/may/chkpnt_fuse_latest.pth'
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /home/xxxx/anaconda3/envs/talkinggaussian/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
Traceback (most recent call last):
  File "metrics.py", line 215, in <module>
    print(lmd_meter.report())
  File "metrics.py", line 102, in report
    return f'LMD ({self.backend}) = {self.measure():.6f}' 
  File "metrics.py", line 96, in measure
    return self.V / self.N
ZeroDivisionError: division by zero

**Comment by Lseonghak** [comment]
I have same issue

**Comment by Fictionarry** [comment]
Hi, I haven't met this problem yet. In my experience, such an "illegal memory access" exception is most likely to appear when CUDA out of memory. However, the required GPU memory for this project is not large. If the target GPU is not occupied, you may try to reinstall the dependencies, especially the gridencoder and 3dgs rasterizer.

**Comment by jisoo-o** [comment]
Thank you for the quick reply! Can you provide which pytorch version you used for CUDA 11.3?
I have used :
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch

I just want to check it is not the torch-cuda matching problem.

**Comment by Fictionarry** [comment]
> Thank you for the quick reply! Can you provide which pytorch version you used for CUDA 11.3? I have used : conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
> 
> I just want to check it is not the torch-cuda matching problem.

Hi, I use pytorch 1.12.1 installed with the same command you provided. It seems not to be a pytorch problem.

**Comment by jisoo-o** [comment]
Thanks, I will retry setting up the environment.
