### ISSUE TITLE
fpn-fp-512.pth

### ISSUE THREAD

**Issue by Z-Times** [Fictionarry/TalkingGaussian#54]
i can't find fpn-fp-512.pth

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Resource>b-ws-620xz-pd11-jux/easyportrait/experiments/models/fpn-fp-512.pth</Resource>
<RequestId>0a0b98ba:19362ac71d1:23c6:2cc9</RequestId>
</Error>

**Comment by Fictionarry** [comment]
Hi, you can download it following these instructions in the README file.

```bash
# download model weight
cd data_utils/easyportrait
wget "https://n-ws-620xz-pd11.s3pd11.sbercloud.ru/b-ws-620xz-pd11-jux/easyportrait/experiments/models/fpn-fp-512.pth"
```

**Comment by Fictionarry** [comment]
> Hi, you can download it following these instructions in the README file.
> 
> ```shell
> # download model weight
> cd data_utils/easyportrait
> wget "https://n-ws-620xz-pd11.s3pd11.sbercloud.ru/b-ws-620xz-pd11-jux/easyportrait/experiments/models/fpn-fp-512.pth"
> ```

I just found there is a 404 error. This is from the repo of https://github.com/hukenovs/easyportrait. Maybe you can try later.
