### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by Z-Times** [Fictionarry/TalkingGaussian#56]
I met this problem and didn't know how to fix it ? Help !!!

**Comment by Fictionarry** [comment]
There may be various situations to cause this error, such as out of GPU memory and pytorch environment conflict. You can first check if the GPU memory is adequate and reinstall pytorch and 3dgs rasterizer following the recommended versions. If the problem remains, you can list more details here so we can locate the problem more easily.
