### ISSUE TITLE
not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by caitongbo** [Fictionarry/TalkingGaussian#7]
Hello, I encountered this error when trying to execute bash scripts/train_xx.sh. Could you please advise on how to resolve it? Thank you!

Traceback (most recent call last):
  File "train_mouth.py", line 328, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_mouth.py", line 139, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/app/dev/TalkingGaussian/gaussian_renderer/__init__.py", line 94, in render
    cov3D_precomp = cov3D_precomp)
ValueError: not enough values to unpack (expected 4, got 3)
Exception ignored in: <function tqdm.__del__ at 0x7f3931f337a0>

**Comment by caitongbo** [comment]
(talking_gaussian) ubuntu@tech-aigc-server:/app/dev/TalkingGaussian$ bash scripts/train_xx.sh 
Optimizing output/wanghui0620
Output folder: output/wanghui0620 [07/07 16:46:10]
Found transforms_train.json file, assuming Blender data set! [07/07 16:46:11]
Reading Training Transforms [07/07 16:46:11]
1914it [00:00, 4252.13it/s]
0 32 [07/07 16:46:11]
1914it [00:27, 68.91it/s]
Reading Test Transforms [07/07 16:46:39]
192it [00:00, 4244.11it/s]
0 32 [07/07 16:46:39]
192it [00:02, 69.19it/s]
Generating random point cloud (10000)... [07/07 16:46:42]
Loading Training Cameras [07/07 16:46:42]
Loading Test Cameras [07/07 16:46:44]
Number of points at initialisation :  10000 [07/07 16:46:44]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off] [07/07 16:46:44]
/home/ubuntu/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
/home/ubuntu/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/ubuntu/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth [07/07 16:46:44]
Training progress:   0%|                                                                                                                                       | 0/50000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_mouth.py", line 328, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_mouth.py", line 139, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/app/dev/TalkingGaussian/gaussian_renderer/__init__.py", line 94, in render
    cov3D_precomp = cov3D_precomp)
ValueError: not enough values to unpack (expected 4, got 3)
Exception ignored in: <function tqdm.__del__ at 0x7f3931f337a0>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/tqdm/std.py", line 1055, in __del__
  File "/home/ubuntu/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/tqdm/std.py", line 1238, in close
  File "/home/ubuntu/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/tqdm/std.py", line 560, in _decr_instances
  File "/home/ubuntu/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/tqdm/_monitor.py", line 51, in exit
  File "/home/ubuntu/miniconda3/envs/talking_gaussian/lib/python3.7/threading.py", line 522, in set
  File "/home/ubuntu/miniconda3/envs/talking_gaussian/lib/python3.7/threading.py", line 365, in notify_all
  File "/home/ubuntu/miniconda3/envs/talking_gaussian/lib/python3.7/threading.py", line 348, in notify
TypeError: 'NoneType' object is not callable

**Comment by Fictionarry** [comment]
It's a bit confusing. The rasterizer we used is a modified version from [diff-gaussian-rasterization](https://github.com/ashawkey/diff-gaussian-rasterization),  which returns 4 tensors. You can try to redownload and reinstall it, which I guess may help.

**Comment by caitongbo** [comment]
> It's a bit confusing. The rasterizer we used is a modified version from [diff-gaussian-rasterization](https://github.com/ashawkey/diff-gaussian-rasterization), which returns 4 tensors. You can try to redownload and reinstall it, which I guess may help.

Thank you! It's running now.
