### ISSUE TITLE
推理后只有脸，其他部分全是黑的，没有背景

### ISSUE THREAD

**Issue by anliyuan** [Fictionarry/TalkingGaussian#9]

**Comment by WangHao-nlp** [comment]
我是只有躯干没有头，而且训练时候psnr很低，感觉有问题

**Comment by Fictionarry** [comment]
试试用script直接跑readme里所提供的training video，如果有问题的话就需要检查一下环境，没问题的话就是素材的问题，分辨率和人像位置都和提供的video相似的情况下应该不会出大问题。最终的结果是out.mp4，不是out_face.mp4，那个是只有脸没背景的

**Comment by anliyuan** [comment]
> 我是只有躯干没有头，而且训练时候psnr很低，感觉有问题

之前为了试验怎么解决噪点的问题，我训练的步数比较多（10w，20w），就会出现这种问题，后来大佬@Fictionarry更新了代码，按照shell训练就可以了，也没有细看原因
